[project]
name = "eadro"
version = "0.1.0"
requires-python = ">=3.12"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "drain3>=0.9.11",
    "fastparquet",
    "numpy",
    "pandas",
    "pyarrow",
    "rich>=13.0.0",
    "ruff",
    "scikit-learn",
    "torch==2.4.0",
    "tqdm",
    "dgl",
    "typer>=0.16.0",
    "loguru>=0.7.3",
    "rcabench>=1.0.47",
    "snakeviz>=2.2.2",
    "flameprof>=0.4",
    "polars>=1.31.0",
    "ipykernel>=6.29.5",
    "pympler>=1.1",
    "dynaconf>=3.2.11",
    "rcabench-platform>=0.2.13",
]
[tool.uv.sources]
dgl = { url = "https://data.dgl.ai/wheels/torch-2.4/cu124/dgl-2.4.0%2Bcu124-cp312-cp312-manylinux1_x86_64.whl" }
torch = { url = "https://download.pytorch.org/whl/cu124/torch-2.4.0%2Bcu124-cp312-cp312-linux_x86_64.whl" }

[dependency-groups]
dev = ["ipykernel>=6.29.5", "jupyter>=1.1.1"]
